#ifndef DEFS_H
#define DEFS_H

#define SERVER_PORT 9301

#define CLIENT_STATUS_CONNECTING 100
#define CLIENT_STATUS_CONNECTED 101
#define CLIENT_STATUS_SENDING_FILE 102
#define CLIENT_STATUS_SEND_FILE_DONE 103
#define CLIENT_STATUS_RECEIVING_FILE 104
#define CLIENT_STATUS_RECEIVE_FILE_DONE 105
#define CLIENT_STATUS_CONNECT_FAILED 200
#define CLIENT_STATUS_SEND_FILE_FAILED 201
#define CLIENT_STATUS_RECEIVE_FILE_FAILED 202

#define CLIENT_COMMAND_SEND_FILE 100

#define SERVER_COMMAND_ACCEPT_FILE 101
#define SERVER_COMMAND_REJECT_FILE 102
#define SERVER_COMMAND_RECEIVE_FILE_SUCCESS 103
#define SERVER_COMMAND_RECEIVE_FILE_FAILED 104

#define BUFFER_SIZE 8192

int getInt(const char *s, int start, int end);

#endif
