######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 10 19:18:21 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += ConnectDialog.h defs.h MainWindow.h
SOURCES += ConnectDialog.cpp main.cpp MainWindow.cpp
