######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 10 19:41:17 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += ConnectDialog.h defs.h MainWindow.h Server.h
SOURCES += ConnectDialog.cpp main.cpp MainWindow.cpp Server.cpp
