######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 10 15:37:02 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += ConnectDialog.h defs.h MainServer.h MainWindow.h
SOURCES += ConnectDialog.cpp main.cpp MainServer.cpp MainWindow.cpp
